return table.freeze {
	BatchRequestType = require "@self/BatchRequestType",
	GroupActionType = require "@self/GroupActionType",
	PresenceType = require "@self/PresenceType",
	SortOrder = require "@self/SortOrder",
	ThumbnailFormat = require "@self/ThumbnailFormat",
	ThumbnailState = require "@self/ThumbnailState",
	UserThumbnailSize = require "@self/UserThumbnailSize",
	UserThumbnailType = require "@self/UserThumbnailType",
}
